---
title: "Bayesian Project"
author: "Abhijith Chigurupati & Vidhi Sharma"
date: '2022-04-10'
output:
  html_document: default
  word_document: default
  pdf_document: default
---

```{r}
library(xts)
library(dplyr)
library("readxl")
## setting working directory
#setwd("C:/Users/asibh/Desktop/DSBA 6010- Bayesian/Project/T9-bvar/Prize Puzzle/Data")
Total_reserves= read.csv('Prize Puzzle/Data/Total reserves.csv')
nb_reserves= read.csv('Prize Puzzle/Data/NONBORRES.csv')
fed_funds_unemp= read.csv('Prize Puzzle/Data/FED_UN_INFLATION_2000-2022.csv')
realgdp_ndef=read.csv('Prize Puzzle/Data/Us-gdp.csv')
CPI= read.csv('Prize Puzzle/Data/CPI (year-year).csv')
```

```{r}
library(lubridate)
Total_reserves$Date<-mdy(Total_reserves$Date)
fed_funds_unemp$Date<- mdy(fed_funds_unemp$Date)
nb_reserves$Date <- mdy(nb_reserves$Date)
realgdp_ndef$Date<-mdy(realgdp_ndef$Date)
CPI$Date<-mdy(CPI$Date)
```

```{r}
df1<- inner_join(Total_reserves,fed_funds_unemp,by='Date')
df2<-inner_join(nb_reserves,realgdp_ndef,by='Date')
df3<-inner_join(df1,df2,by='Date')
df<-inner_join(df3,CPI)

```

Causal Paths: (Still need to update further)
1)	Inflation > threshold > Fed polic> Fed rate or to Increase CRR > Non borrow > interest rate
2)	FED policy > changes in MS > Total Reserves > Interest rate > Inflation
3)	Real GDP> Prices change or interest rate  > CPI >   ngdp > unemployment 
4)	Inflation > gdp > CPI > Unemployment


```{r}
library(dagitty)
library(ggdag)
g<- dagitty('
dag {
"GDP Deflator" [outcome,pos="1.040,-1.230"]
"Interest Rate" [pos="-1.998,0.068"]
"Monetary Policy" [latent,pos="-0.151,1.235"]
"Non Borrowed Reserves" [pos="-0.718,0.514"]
CPI [outcome,pos="1.338,-0.175"]
Fed_Fund_rate [pos="-2.097,1.182"]
GDP [exposure,pos="-0.073,-1.585"]
Investment [adjusted,pos="-1.030,-0.903"]
Savings [adjusted,pos="-1.901,-1.047"]
Unemployment [exposure,pos="-1.929,-1.691"]
"GDP Deflator" -> GDP
"Interest Rate" -> "GDP Deflator"
"Interest Rate" -> CPI
"Interest Rate" -> Investment
"Interest Rate" -> Savings
"Monetary Policy" -> "Non Borrowed Reserves"
"Monetary Policy" -> Fed_Fund_rate
"Non Borrowed Reserves" -> "Interest Rate"
CPI -> "GDP Deflator"
CPI -> "Monetary Policy"
Fed_Fund_rate -> "Interest Rate"
GDP -> Unemployment
Investment -> GDP
Savings -> GDP
}
')
plot(g)

ggdag::ggdag_status(g, text = FALSE, use_labels = "name") +
  guides(color = "none") +  # Turn off legend
  theme_dag()
```
```{r}
install.packages("Rcpp")
install.packages("ggplot2")
devtools::install_github("kthohr/BMR")
```


